[book]
authors = ["Sergey Bugaev"]
language = "en"
multilingual = false
src = "src"
title = "peel documentation"

[output.html]
smart-punctuation = true
git-repository-url = "https://gitlab.gnome.org/bugaevc/peel"
git-repository-icon = "fa-gitlab"
edit-url-template = "https://gitlab.gnome.org/bugaevc/peel/edit/main/docs/{path}"

[output.html.code]
hidelines = { cpp = "$", python = "~" }
